-- ⚠️ 제안(REVIEW-ONLY) — 자동 적용 금지. 사람이 검토 후 의도적으로 멀티유저 전환할 때만 실행.
-- overnight/2026-06-21-hardening 점검 산출물. schema.sql 은 손대지 않았다(이 파일은 별도 마이그레이션 제안).
--
-- ─────────────────────────── 진단 ───────────────────────────
-- 현재(schema.sql) RLS = 세 테이블 모두 `for all to authenticated using(true) with check(true)`.
--   · episodes / vocab_cards : 공용 카탈로그(팟캐스트 콘텐츠) → 모든 로그인 유저가 읽어도 무방. (프라이버시 X)
--   · srs_cards              : 한 테이블에 '카탈로그(front/back/category)' + '유저별 복습상태(ease/interval_days/
--                              due_date/reps)' 가 섞여 있고 user_id 가 없다.
--
-- 오늘 상태: 앱은 의도적 단일 사용자(README §4 = 계정 1개) → 유저가 1명이라 활성 누수 없음.
--            anon 은 RLS 로 차단되므로 publishable 키/URL 이 공개돼도 데이터는 안전.
--
-- 잠재 위험(멀티유저 전환 시): `using(true)` 라 인증된 모든 유저가 srs_cards 전 행을 read/write.
--   → 2번째 계정이 생기면 두 유저가 같은 복습상태를 공유·덮어써서 (1) 진도 충돌(데이터 무결성),
--     (2) 타인의 복습상태 열람/수정(프라이버시) 이 동시에 발생한다.
--   동일 패턴이 cnpod-review 에도 그대로 있으므로 거기서도 같은 전환이 필요하다.
--
-- 왜 단순히 srs_cards 에 user_id 만 붙이면 안 되나:
--   srs_cards 행은 ingest(service_role)가 vocab 으로부터 '전역 1벌' 로 생성한다(ingest/store.py
--   insert_vocab_and_srs). 카드 자체(front/back)는 공용 카탈로그이고, '복습상태' 만 유저별이다.
--   → 카탈로그와 유저상태를 분리하는 것이 정석(권장: 옵션 A). 단일 테이블 유지(옵션 B)는 카드를
--     유저마다 복제해야 해 비정규화·ingest 팬아웃이 필요하다.

-- ═══════════════════════════ 옵션 A (권장): 복습상태 분리 ═══════════════════════════
-- srs_cards 는 '공용 카탈로그'(읽기 전용)로 남기고, 유저별 진도는 새 테이블 srs_progress 로.

create table if not exists srs_progress (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null default auth.uid() references auth.users(id) on delete cascade,
  card_id       bigint not null references srs_cards(id) on delete cascade,
  ease          double precision default 2.5,
  interval_days integer default 0,
  due_date      date not null default current_date,
  reps          integer default 0,
  updated_at    timestamptz default now(),
  unique (user_id, card_id)
);
create index if not exists idx_srs_progress_user_due on srs_progress(user_id, due_date);

alter table srs_progress enable row level security;
drop policy if exists "own progress" on srs_progress;
create policy "own progress" on srs_progress
  for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());
grant select, insert, update, delete on srs_progress to authenticated;

-- 기존 단일 유저의 진도를 보존하려면(전환 시점에 유저가 1명일 때) 1회 백필:
--   insert into srs_progress (user_id, card_id, ease, interval_days, due_date, reps)
--   select (select id from auth.users order by created_at limit 1),
--          id, ease, interval_days, due_date, reps
--   from srs_cards
--   on conflict (user_id, card_id) do nothing;

-- 카탈로그 3종은 인증 유저에게 '읽기 전용'(쓰기는 ingest=service_role 만). 공개 publishable 키가
-- 노출돼도, 로그인 세션이 카탈로그를 변조하지 못하게 하는 심층방어.
drop policy if exists "authenticated all" on episodes;
drop policy if exists "authenticated all" on vocab_cards;
drop policy if exists "authenticated all" on srs_cards;
create policy "auth read" on episodes    for select to authenticated using (true);
create policy "auth read" on vocab_cards for select to authenticated using (true);
create policy "auth read" on srs_cards   for select to authenticated using (true);
revoke insert, update, delete on episodes, vocab_cards, srs_cards from authenticated;

-- 앱 코드(db.js) 변경 필요(옵션 A 채택 시):
--   · srsQueue() : srs_cards(카탈로그) ⨝ srs_progress(내 진도) 조인. 진도 없는 카드는 신규(reps=0,
--                  due=today)로 취급. due/reps 필터는 srs_progress 기준.
--   · srsReview(): srs_progress 행을 upsert(user_id 는 default auth.uid()).
--   · markKnown()/markUnknown()/studyOverview(): srs_cards 대신 srs_progress 의 interval_days/reps 기준.

-- ═══════════════════════════ 옵션 B (단순·비정규화) ═══════════════════════════
-- 스키마/앱 변경을 최소화하려면 srs_cards 에 user_id 를 추가하고 유저별로 카드를 복제한다.
-- 단점: 카드 본문이 유저 수만큼 중복되고, ingest 가 '유저마다' srs_cards 를 fan-out 해야 한다.
--   alter table srs_cards add column user_id uuid default auth.uid() references auth.users(id);
--   update srs_cards set user_id = (select id from auth.users order by created_at limit 1) where user_id is null;
--   alter table srs_cards alter column user_id set not null;
--   drop policy if exists "authenticated all" on srs_cards;
--   create policy "own cards" on srs_cards for all to authenticated
--     using (user_id = auth.uid()) with check (user_id = auth.uid());
-- (episodes/vocab_cards 는 공용 카탈로그라 옵션 A 의 읽기전용 정책을 그대로 사용.)

-- ─────────────────────────── 검증 시나리오 (2-유저) ───────────────────────────
-- 1) 대시보드에서 계정 B 를 추가(Auto Confirm).
-- 2) A 로 로그인 → SRS 몇 장 채점(reps↑, due 변경) → 진도 기록.
-- 3) B 로 로그인 → SRS 큐가 '초기상태'(A 의 진도가 안 보임)인지 확인. B 채점 후
--    다시 A 로 로그인 → A 진도가 B 채점에 영향받지 않았는지 확인(상호 불가시성).
-- 4) (옵션 A) `select count(*) from srs_progress where user_id <> auth.uid()` 를 각 세션에서
--    실행 시 0 행이어야 한다(RLS 가 타 유저 행을 가린다).
