-- aep-review Supabase 스키마
-- Supabase 대시보드 → SQL Editor 에 붙여넣고 실행.
-- api/db.py 의 SQLite SCHEMA 를 Postgres 로 포팅 + RLS + Storage 버킷.
--
-- 설계 메모:
--  * id 는 `generated by default as identity` — 마이그레이션이 기존 SQLite id 를
--    그대로 넣어야 episode_id/vocab_id 참조가 보존되므로 명시 insert 를 허용한다.
--    (이관 후 reset_id_sequences() 로 시퀀스를 max(id) 로 맞춘다)
--  * audio_path / transcript_path(로컬 FS 경로) 는 제거 — 클라우드에선 무의미.
--    오디오는 audio_url(CDN) 직접 스트리밍, transcript 는 Storage 규약 경로로 접근.
--  * 개인앱 → 모든 테이블 RLS = authenticated 전체 허용 / anon 차단.

-- ─────────────────────────── 테이블 ───────────────────────────
create table if not exists episodes (
  id                 bigint generated by default as identity primary key,
  guid               text unique not null,
  season             integer,
  episode_no         integer,
  title              text not null,
  pub_date           timestamptz,
  duration_sec       integer,
  description        text,
  audio_url          text,
  transcribed_at     timestamptz,
  vocab_extracted_at timestamptz,
  created_at         timestamptz default now()
);
create index if not exists idx_episodes_pub on episodes(pub_date desc);

create table if not exists vocab_cards (
  id                 bigint generated by default as identity primary key,
  episode_id         bigint references episodes(id) on delete cascade,
  term               text not null,
  kind               text,
  definition         text,
  example_sentence   text,
  sentence_start_sec double precision,
  sentence_end_sec   double precision,
  created_at         timestamptz default now()
);
create index if not exists idx_vocab_episode on vocab_cards(episode_id);

create table if not exists srs_cards (
  id            bigint generated by default as identity primary key,
  episode_id    bigint references episodes(id) on delete cascade,
  vocab_id      bigint references vocab_cards(id) on delete cascade,
  front         text not null,
  back          text not null,
  category      text,
  ease          double precision default 2.5,
  interval_days integer default 0,
  due_date      date not null,
  reps          integer default 0,
  created_at    timestamptz default now()
);
create index if not exists idx_srs_due on srs_cards(due_date);

-- ───────────────────── 뷰: /api/episodes 모양 보존 ─────────────────────
-- security_invoker → 조회하는 사용자(authenticated)의 RLS 가 그대로 적용됨.
create or replace view episodes_list with (security_invoker = true) as
select
  e.id, e.guid, e.season, e.episode_no, e.title, e.pub_date, e.duration_sec, e.description,
  (e.audio_url is not null) as has_audio,
  e.transcribed_at, e.vocab_extracted_at, e.audio_url,
  (select count(*) from vocab_cards v where v.episode_id = e.id) as vocab_count
from episodes e;

-- ─────────────────────────── RLS ───────────────────────────
alter table episodes    enable row level security;
alter table vocab_cards enable row level security;
alter table srs_cards   enable row level security;

drop policy if exists "authenticated all" on episodes;
drop policy if exists "authenticated all" on vocab_cards;
drop policy if exists "authenticated all" on srs_cards;

create policy "authenticated all" on episodes
  for all to authenticated using (true) with check (true);
create policy "authenticated all" on vocab_cards
  for all to authenticated using (true) with check (true);
create policy "authenticated all" on srs_cards
  for all to authenticated using (true) with check (true);

grant select, insert, update, delete on episodes, vocab_cards, srs_cards to authenticated;
grant select on episodes_list to authenticated;

-- ──────────────── 마이그레이션 후 id 시퀀스 보정용 RPC ────────────────
-- 명시 id 로 행을 넣은 뒤 호출 → 다음 자동 id 가 max(id)+1 부터 나오게 한다.
create or replace function public.reset_id_sequences()
returns void language plpgsql security definer as $$
begin
  perform setval(pg_get_serial_sequence('episodes',    'id'), coalesce((select max(id) from episodes),    1));
  perform setval(pg_get_serial_sequence('vocab_cards',  'id'), coalesce((select max(id) from vocab_cards), 1));
  perform setval(pg_get_serial_sequence('srs_cards',    'id'), coalesce((select max(id) from srs_cards),   1));
end;
$$;
grant execute on function public.reset_id_sequences() to service_role, authenticated;

-- ─────────────────────────── Storage 버킷 ───────────────────────────
-- public read (비민감 미디어). 업로드는 service_role 키(마이그레이션/인제스트)만.
insert into storage.buckets (id, name, public) values ('transcripts', 'transcripts', true)
  on conflict (id) do nothing;
insert into storage.buckets (id, name, public) values ('tts', 'tts', true)
  on conflict (id) do nothing;
